### ISSUE TITLE
Allow account_linking type event to propagate from webhook to allow handling

### ISSUE THREAD

**Issue by ShoukriKattan** [Charca/bootbot#1]
First of all thanks for the awesome library!! Nicely written and architected! 

Facebook's latest Webhook reference (https://developers.facebook.com/docs/messenger-platform/webhook-reference/account-linking) supports account linking process to Link Messenger account to 3rd party accounts. It will be nice If Bootbot will allow account_linking type event to propagate.   

This is a one line change, that I will be happy to submit, or feel free to add it or let me know if it does not make any sense. 

In Bootbot.js   in `_initWebhook` function: 

`  if (event.optin) {`
             ......
`
            } else {
              console.log('Webhook received unknown event: ', event);
            }`

before the final else add a new line 

`    if (event.optin) {`
....
` } else if (event.read) {`
`              this._handleEvent('read', event);`
`            }else if (event.account_linking){   // Add this to support account linking `
`            this._handleEvent('account_linking', event); // Add this to support account linking`
`           } else {`
`              console.log('Webhook received unknown event: ', event);`
`            }`

Thanks in advance

**Comment by Charca** [comment]
Hey @ShoukriKattan, thanks for the suggestion! I've added support for `account_linking` events on the latest version: 1.0.6

Thanks again, and feel free to submit a PR next time :)

Diff: https://github.com/Charca/bootbot/commit/5feabaac3d1a313114504e1aa5ec8825bb88235d
