### ISSUE TITLE
Get users email

### ISSUE THREAD

**Issue by jaksz** [Charca/bootbot#102]
We can get the users profile with chat.getUserProfile(), but how can we get the email?

**Comment by mraaroncruz** [comment]
Here's an article about it. It looks like a real pain. Look in the comments, there's some good stuff.
http://espeo.eu/blog/user-permissions-messenger-bots/

Also look here https://developers.facebook.com/docs/messenger-platform/webview/permissions
I can't see anything about email here: https://developers.facebook.com/docs/messenger-platform/identity/user-profile

It looks like it's a bit of a black art.

**Comment by mraaroncruz** [comment]
Also check out this https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow
linked to in this related thread in the botkit repo
https://github.com/howdyai/botkit/issues/544

**Comment by FnTm** [comment]
@jaksz I'm quite certain that e-mail is not something you can get directly from the userProfile, and that is by design. Your best option is to ask the user to enter their e-mail directly in some way, though most users will most likely not do that.

**Comment by Charca** [comment]
Yeah, I don't think it's possible to get the user's email address from Facebook. This might change in the future, but right now your best option is to ask the user directly.
