### ISSUE TITLE
No matching user found?

### ISSUE THREAD

**Issue by danielnjoo** [Charca/bootbot#109]
Creating a `hello world` app with this package (have made others before),  and currently am receiving responses, but am unable to send replies, via `chat.say()`?

```
bot.hear('hi', (payload, chat) => {
  console.log('message received')
  chat.say('hello');
});
```

Any tips?

**Comment by mraaroncruz** [comment]
It sounds like you're sending replies to the wrong page. Make sure your access token is set to the correct page.
User ID's are not facebook ids, they are scoped to the page. So you may be sending messages to user ids for the wrong page and this is how facebook would respond.

**Comment by danielnjoo** [comment]
Thanks! I had the wrong page access token (too many pages / apps)... was testing for a workshop that I'm running.

**Comment by mraaroncruz** [comment]
I knew where to look because I have had the same issue a few times ;)

I'm glad it worked for you!
