### ISSUE TITLE
issue on postback :BOOTBOT_GET_STARTED

### ISSUE THREAD

**Issue by c0nstructer** [Charca/bootbot#118]
When doing conversation, and suddenly deleting chat, and hitting get started button,
bot thinks that it is still in conversation, thus it does not recognize payload message.

Waiting for minute, deleting again conversation, bot knows that it is dropped out of conversation, and starts normally.

**Comment by mraaroncruz** [comment]
I don't know what to tell you here. This is a facebook issue and not a usecase that I think we care about.
You should have a new page specific user id after you delete your chat. This is how the bot would see it wasn't in a conversation anymore (completely new user id). If facebook is taking too long to update this, there's nothing we can do here.
