### ISSUE TITLE
Saving Data in Mongo?

### ISSUE THREAD

**Issue by tdelam** [Charca/bootbot#127]
Hi,

Are there any examples or documentation as to how to save responses into mongo?

**Comment by Azique** [comment]
Hi, could you provide a bit more details about what you're trying to accomplish?
Since in general storing a sting (array of strings) in mongo is pretty straightforward my guess is that it's not what you're looking for

**Comment by mraaroncruz** [comment]
@tdelam how do you normally store things in Mongo?

**Comment by tdelam** [comment]
Sorry, yah storing is simple but I mean... I am looking for a concept like a middleware. I didn't see anything about middleware in the docs so I am guessing this is not a thing with bootbot?

**Comment by mraaroncruz** [comment]
Bootbot runs on top of express. You can access the express app via:
```js
const bot = new Bootbot({args});
const expressApp = bot.app;
```
There are a couple middleware related PR's too. Maybe some of the discussion can help.
https://github.com/Charca/bootbot/pull/104
https://github.com/Charca/bootbot/pull/107
