### ISSUE TITLE
Deploying to Heroku?

### ISSUE THREAD

**Issue by tdelam** [Charca/bootbot#130]
My bot is done, looking for some docs on deploying but didn't find any. Any tips? The tunnel seems to start up and listens on localhost on heroku... I do have some log entries though:

`2018-05-14T17:45:31.653849+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path= "/webhook?hub.mode= subscribe&hub.challenge= 733323090&hub.verify_token=delamorandiere" host=fast-lowlands-28084.herokuapp.com request_id=31aaa7e9-4372-42e6-988c-7d6ae11871c3 fwd="66.220.152.164" dyno= connect= service= status=503 bytes= protocol=https`

**Comment by MaelLarcher** [comment]
I have the same issue, how did you solve this ?
