### ISSUE TITLE
Webhook received unknown event

### ISSUE THREAD

**Issue by libhide** [Charca/bootbot#131]
Hey, I'm trying to follow the following example from the docs:

```
const question = {
  text: questions[convo.get('questionNumber', questionNumber)],
  quickReplies: [
    {
      "content_type": "text",
      "title": "",
      "payload": "YES",
      "image_url": "YES_IMAGE_URL"
    },
    {
      "content_type": "text",
      "title": "",
      "payload": "NO",
      "image_url": "NO_IMAGE_URL"
    }
  ]
};

const answer = (payload, convo) => {
  // Nothing here
};

const callbacks = [
  {
    event: 'quick_reply:YES',
    callback: (payload, convo) => {
      console.log("YES"); // this just doesn't get printed
    },
    event: 'quick_reply:NO',
    callback: (payload, convo) => {
      console.log("NO");  // this just doesn't get printed
    }
  }
];

const options = {
  typing: true // Send a typing indicator before asking the question
};

convo.ask(question, answer, callbacks, options);
```

and the console is throwing out a "Webhook received unknown event" at me.

![the issue](http://oi65.tinypic.com/20qyu5k.jpg "Issue")

What am I doing wrong here?

**Comment by mraaroncruz** [comment]
The error that is happening is that bootbot is expecting there to be a `text` key inside of your `event.message` object. Since it doesn't see this, it doesn't understand what is going on.
I have never heard of this happening so my guess is either:
- Facebook changed the API
- You're sending in the event data and it is malformed (missing the text key in message)
- Facebook bug

You can see the `text` under "Webhook Event" here https://developers.facebook.com/docs/messenger-platform/send-messages/quick-replies#text

**Comment by libhide** [comment]
Yeah, it turns out that I do need to pass in something as `text`. Although, this is a `BootBot` restriction and not something Facebook caused since I've made quick replies work without sending text before. 

Any idea on how I can achieve what I want to achieve (not sending text) and still continue using `BootBot`?

**Comment by mraaroncruz** [comment]
What do you mean by "sending text". I don't understand your use case. AFAIK facebook requires text with all quick replies. But this is maybe me just being in a bootbot echo chamber.

Also, according to the docs, `text` or `attachment` must be set.
<img width="820" alt="quick_replies_-_messenger_platform" src="https://user-images.githubusercontent.com/175984/40873282-cc5cce28-665d-11e8-8dc0-801de6703403.png">

**Comment by libhide** [comment]
I think there is a confusion between`text` and `title` – my bad.
I'm definitely sending a `text` with the quick-reply but want to try and avoid sending a `title`. According to the docs, this is possible. 

![title](https://user-images.githubusercontent.com/1370559/40877163-c284239c-6699-11e8-8ca6-1b66b48e8bcc.jpg)

Thoughts?

**Comment by mraaroncruz** [comment]
If you send a quickreply, you need to set `text`. You are not setting `text`. That is why you are receiving the error. If you set `text` everything else should be fine. Follow my link to the calling bootbot code above if you still aren't following what I'm talking about.
