### ISSUE TITLE
Messenger Error Handling

### ISSUE THREAD

**Issue by DerekNMartin** [Charca/bootbot#148]
How would I go about handling a messenger error?
(ex.` '(#100) Length of param message[text] must be less than or equal to 2000',`)

It seems like there's no way to catch the error since it seems like the response isn't returned, only console logged.

**Comment by Charca** [comment]
@DerekNMartin the Send API methods return a promise, so you should be able to use a `catch` statement like:

```
chat.say('hello world')
  .then(() => console.log('success'))
  .catch(() => console.log('handle error here'))
```

Is that not working for you?
