### ISSUE TITLE
How to see debug messages or logs?

### ISSUE THREAD

**Issue by MMayla** [Charca/bootbot#22]
When I send templates sometimes it didn't show in chat and I don't know what is the reason.

But after a long time trying I discover a syntax error in my template or my elements has more than the maximum allowed elements. This errors are easy to solve but sometimes hard to find.

So is there any logs that I can see? or any debug event?

**Comment by kebou** [comment]
Hey @MMayla, you can check the error property of the response object, the error codes are listed on this [site](https://developers.facebook.com/docs/messenger-platform/send-api-reference/errors).
See the example below:

``` javascript
bot.sendGenericTemplate(userId, elements).then((res) => { 
    if (res.error) console.log('Failed to send Generic Template: ' + JSON.stringify(res) );
});
```

**Comment by MMayla** [comment]
@kebou thank you :+1:

**Comment by Charca** [comment]
FYI @MMayla and @kebou, I've just added a generic error message when Facebook responds with the `error` node so you don't have to manually debug it. Thanks for the suggestion!

![ErrorMsg](http://c.hlp.sc/3l2h2u3w0p16/Image%202017-02-23%20at%2011.01.28%20PM.png)
