### ISSUE TITLE
Support v1.4 new features

### ISSUE THREAD

**Issue by Charca** [Charca/bootbot#26]
Messenger Platform 1.4 is out today with a lot of juicy new updates!

Make sure we support all of them: https://messengerblog.com/platform-updates/messenger-platform-1-4-brings-even-more-tools-to-build-great-experiences/

**Comment by Ltty** [comment]
Do you already have a timeline for the updated API?

**Comment by Charca** [comment]
Hey @Ltty, thanks again for your contribution. Your PR takes care of all updates for the new Messenger Profile API, so after we merge that, we should be good to go!

The only new feature we need to support is the `image_aspect_ratio` prop in `sendGenericTemplate()` ([docs](https://developers.facebook.com/docs/messenger-platform/send-api-reference/generic-template#payload)). I can take care of that in a separate PR.

**Comment by tmwd** [comment]
What about referral param?
https://developers.facebook.com/docs/messenger-platform/referral-params
Maybe it could be handful to have an emitter for that?

**Comment by Charca** [comment]
@tmwd I've added support for the referral event in https://github.com/Charca/bootbot/commit/df179c55a10596c646188131d5c001ea3993150d

Once we merge @Ltty's PR we'll be able to close this issue.

**Comment by tmwd** [comment]
@Charca 
Well, refs is not firing, this what I have instead:
"Webhook received unknown event:"

**Comment by tmwd** [comment]
@Charca 
Since there is no way handle event if its not in the release, maybe it will be useful to have default handler for unknown events?

**Comment by Charca** [comment]
@tmwd I've just published v1.0.11 that should give you the ability to listen for the referral event with `bot.on('referral', callback)`.

As for the generic "catch-all" handler for unknown events, I'd prefer to keep it controlled for now. I wouldn't like people to use this event for new features and never switching to the actual event when the framework adds support for it. Also this event wouldn't generate a `Chat` instance because we couldn't guarantee that there's a sender object in the payload.

If in the future Facebook starts adding events faster than we can keep up with, I can consider adding it, but for now I'd rather keep it under control.

**Comment by Charca** [comment]
v1.0.12 released with full support for Messenger v1.4: https://github.com/Charca/bootbot/releases/tag/v1.0.12
