### ISSUE TITLE
Middleware Support [Feature Request]

### ISSUE THREAD

**Issue by SawyerHood** [Charca/bootbot#3]
Hey @Charca , I saw your post about BootBot in the Bots Facebook group and after looking at the framework, I really want to try BootBot for my next Messenger bot. I've been using NLP services in most of my bots (specifically Wit.ai) however and would love it if BootBot had support for middleware to do additional processing when a message is received. I could use `bot.on('message')` to process messages with Wit.ai, but there wouldn't be a way to dispatch on these results using `bot.hear()`. My solution to this is allowing the BootBot to accept middleware, which are executed when a message is received and add a context which `hear()` can use to dispatch on. Here is some pseudocode of how it could be used:

``` javascript
'use strict';
const BootBot = require('bootbot');

const bot = new BootBot({
  accessToken: 'FB_ACCESS_TOKEN',
  verifyToken: 'FB_VERIFY_TOKEN',
  appSecret: 'FB_APP_SECRET'
});

// A middleware returns a promise that when resolved adds context
// that can be used to dispatch on hear messages
// hear callbacks are not executed until all middleware have been resolved
bot.addMiddleware((message) => fetchWitAiIntent(message).then(
  (witAiResult) => {witai: {intent: witAiResult.userIntent}}
));

// a predicate can be used to decide what response should be triggered by the bot
function userHungry(payload, middlewareContext) {
  return middlewareContext.witAi.intent === 'hungry';
}

// predicate used to determine if case should be executed
bot.hear(['food', userHungry], (payload, chat, middlewareContext) => {
  // Do something here.
});
```

I don't know if middleware is in the roadmap or not. Let me know what you think, and if you are fine with it I would love to implement it.

**Comment by Charca** [comment]
Hey @SawyerHood, this is a great suggestion. I wasn't planning on adding middleware support right now, but anything that helps integrating other services (specially NLP services) it's in the roadmap!

I like your initial proposal, I'll run a few experiments during the weekend to get a better feel of it, but please feel free to submit a PR implementing this feature. Can't wait to see it!

**Comment by SawyerHood** [comment]
@Charca, I'm slammed this weekend but during the week I'll think through it and try to throw something together that works well with existing features (including conversations). Keep me posted on what you experiment with and what you think up to integrate 3rd party platforms into BootBot.

**Comment by sdc-rafael** [comment]
any advance on this? NLP services intregrations are a must :)

**Comment by pferdefleisch** [comment]
@sdc-rafael this issue isn't specifically about NLP services. You could solve that with something like this:

```js
bot.hear('ask me something', (payload, chat) => {
    chat.conversation((convo) => {
        askName(convo);
    });

    const askName = (convo) => {
        convo.ask(`What's your name?`, (payload, convo) => {
            const text = payload.message.text;
            // made up wit.ai api wrapper code
            const nlpResponseText = Wit.response(payload.sender.id, text)
            convo.say(nlpResponseText);
            convo.end();
        });
    };
});
```

Though it would be nice to have something like microsoft bot framework's [`intentDialog`](https://docs.botframework.com/en-us/node/builder/guides/understanding-natural-language/#handle-intents) but that's for a different issue.

**Comment by pferdefleisch** [comment]
What do you think about closing this one @Charca? Last comment in October and there is a workaround/fix.

**Comment by Charca** [comment]
Yep, I'm going to close this one. Thanks everyone for the comments and the workaround!
