### ISSUE TITLE
Postback doesn't work for example in your example (threads-example.js) it should give you saying response if you click on help or sittings but it didn't

### ISSUE THREAD

**Issue by Obadh** [Charca/bootbot#33]
`bot.setPersistentMenu([
  {
    type: 'postback',
    title: 'Help',
    payload: 'PERSISTENT_MENU_HELP'
  },
  {
    type: 'postback',
    title: 'Settings',
    payload: 'PERSISTENT_MENU_SETTINGS'
  },
  {
    type: 'web_url',
    title: 'Go to Website',
    url: 'http://yostik.io'
  }
]);

bot.on('postback:PERSISTENT_MENU_HELP', (payload, chat) => {
  chat.say(`I'm here to help!`);
});

bot.on('postback:PERSISTENT_MENU_SETTINGS', (payload, chat) => {
  chat.say(`Here are your settings: ...`);
});`

**Comment by Charca** [comment]
Hey @Obadh, are you getting any errors when trying to use this example? I just tested it and it seems to be working correctly for me: http://c.hlp.sc/3S2C0J2z1w3W
