### ISSUE TITLE
Persistent menu: Invalid keys "call_to_actions" were found in param "call_to_actions[0]"

### ISSUE THREAD

**Issue by sotirelisc** [Charca/bootbot#37]
The example (and another nested persistent menu that I tried) gives the above error or a similar one. The implementation may be correct but I cannot seem to find the right way to use the new menu, right now. :P

**Comment by Charca** [comment]
Hey @sotirelisc, have you updated bootbot to the latest version (1.0.12)? Can you paste the example that is giving you this error?

**Comment by sotirelisc** [comment]
@Charca, I used the exact example from the examples directory.

**Comment by Charca** [comment]
@sotirelisc, I just checked and you'll get this error if you try to use the example with a bootbot version prior to 1.0.12, please update with `npm install bootbot --save` if you want to use this feature.

**Comment by sotirelisc** [comment]
@Charca, are you sure? I have it updated (also on Heroku) but it still gives me the same error.

**Comment by pferdefleisch** [comment]
Do you have a stack trace @sotirelisc?

**Comment by sotirelisc** [comment]
No stack trace just this:

```
{ message: '(#100) Invalid keys "call_to_actions" were found in param "call_to_actions[0]".',
type: 'OAuthException',
code: 100,
fbtrace_id: 'A8g3gEPeyCx' }
```

**Comment by Charca** [comment]
I'll re-open this issue while we investigate. @sotirelisc can you check that the `package.json` file in your `node_modules/bootbot/` folder has the correct version number? It should look like this:

![img](https://d3vv6lp55qjaqc.cloudfront.net/items/3C462h1H2B1Z2o471T11/Image%202017-04-18%20at%202.53.34%20PM.public.png?v=54ae89ca)

**Comment by sotirelisc** [comment]
Oh, it seems that neither "npm update" nor "install" worked for some reason and kept an earlier version of BootBot. I manually changed the `package.json` and now it works! Thank you and sorry!
