### ISSUE TITLE
How to trigger an event programmatically ?

### ISSUE THREAD

**Issue by MMayla** [Charca/bootbot#39]
Let's say I have an event like this
```
bot.on('postback:HELP', (payload, chat) => {
  chat.say('need help');
});
```
how to trigger this event when for example the user says "help"
```
bot.hear('help', (payload, chat) => {
  // trigger "postback:HELP"
});
```

**Comment by pferdefleisch** [comment]
I would extract it to a function

```javascript
function handleHelp(payload, chat) {
  chat.say('need help');
}

bot.on('postback:HELP', (payload, chat) => {
  handleHelp(payload, chat);
});

bot.hear('help', (payload, chat) => {
  handleHelp(payload, chat);
});
```

**Comment by MMayla** [comment]
Thanks @pferdefleisch 
But is there any other way to trigger the postback event?

**Comment by Charca** [comment]
@MMayla the bot object is an instance of Node's EventEmitter, so if you want to trigger an event you can call `bot.emit('postback:HELP', payload, chat, other, params)'`.

**Comment by MMayla** [comment]
Thanks @Charca
