### ISSUE TITLE
Account Linking

### ISSUE THREAD

**Issue by ansarizafar** [Charca/bootbot#4]
Is it possible to use account linking feature with bootbot?

**Comment by Charca** [comment]
Hi @ansarizafar, yes you can use Account Linking with BootBot. You can subscribe to the `account_linking` event with your `bot` instance. For example:

```javascript
bot.on('account_linking', (payload, chat) => {
  const status = payload.account_linking.status;
  // status will be 'linked' or 'unlinked'
});
```

Your `payload` will have the format specified in the [Account Linking Documentation](https://developers.facebook.com/docs/messenger-platform/webhook-reference/account-linking)

And to send a Login or Logout button, you can use any of the methods provided by bootbot like `sendButtonTemplate` or `sendGenericTemplate`. For example:

```javascript
chat.sendGenericTemplate([{
  "title": "Welcome to M-Bank",
  "image_url": "http://www.example.com/images/m-bank.png",
  "buttons": [{
    "type": "account_link",
    "url": "https://www.example.com/oauth/authorize"
  }]
}]);
```

Let me know if you have any other questions ;)

**Comment by Charca** [comment]
Added a wiki entry with this information: https://github.com/Charca/bootbot/wiki/Account-Linking

**Comment by cAstraea** [comment]
Can someone explain what should be at example.com/oauth/authorize ? Been having a go at this for the past week. Kinda tried to make a backend with express and passport and passport-facebook and it semi works but I don't know where or how to redirect back to the bot.  There's lots of missing elements and couldn't find a concrete example or tutorial anywhere online. 

For example in here what would the redirect uri and redirect uri success be ? Should it be the m.me/ the address to my bot ? 
```
App.get ('/ authorize', function (req, res) { 
var accountLinkingToken = req.query.account_linking_token; 
var redirectURI = req.query.redirect_uri; 
var authCode = "1234567890"; 
var redirectURISuccess = redirectURI + "& authorization_code = + AuthCode;

Res.render ('authorize', { 
accountLinkingToken: accountLinkingToken, 
redirectURI: redirectURI, 
redirectURISuccess: redirectURISuccess 
}); 
});
```
