### ISSUE TITLE
Add other webhooks

### ISSUE THREAD

**Issue by jokamjohn** [Charca/bootbot#40]
I am trying to use the api.ai webhook but i am getting an error.

Error: Couldn't validate the request signature.
    at BootBot._verifyRequestSignature (F:\Bot\Plan_Arvana\node_modules\bootbot\lib\BootBot.js:445:13)
    at F:\Bot\Plan_Arvana\node_modules\body-parser\lib\read.js:100:9
    at invokeCallback (F:\Bot\Plan_Arvana\node_modules\raw-body\index.js:262:16)
    at done (F:\Bot\Plan_Arvana\node_modules\raw-body\index.js:251:7)
    at IncomingMessage.onEnd (F:\Bot\Plan_Arvana\node_modules\raw-body\index.js:307:7)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

anyhelp??

**Comment by pferdefleisch** [comment]
What api.ai webhook are you talking about?
bootbot only accepts webhook requests from facebook. bootbot is telling you that the verify signature of whatever is sending bootbot the message at its webhook is incorrect. Facebook hashes the body of the message they send together with your messenger bot's facebook app secret.
Here's the code in bootbot: https://github.com/Charca/bootbot/blob/master/lib/BootBot.js#L442-L458
Here're the messenger docs: https://developers.facebook.com/docs/messenger-platform/webhook-reference#security
And here's an interesting article about why it's necessary: https://chatbotsmagazine.com/how-to-kill-a-bot-with-10-http-requests-ca7eb57c2ad1

To use another webhook system (if api.ai has such a thing), you could add more express endpoints, I believe, by pulling the `app` attribute out of the bot you instantiate. Here's a maybe working example:

```javascript
'use strict';
const BootBot = require('bootbot');

const bot = new BootBot({
  accessToken: 'FB_ACCESS_TOKEN',
  verifyToken: 'FB_VERIFY_TOKEN',
  appSecret: 'FB_APP_SECRET'
});

// Here's where you add your webhook
// this needs to be added before your call to bot.start() below
this.app.post('/my/apiai/webhook', (req, res) => {
      var data = req.body;
      // handle api.ai webhook data here
})

bot.on('message', (payload, chat) => {
  const text = payload.message.text;
  chat.say(`Echo: ${text}`);
});

bot.start();
```

**Comment by jokamjohn** [comment]
Thank you.

**Comment by Juan-Pieterse** [comment]
Guys. I got the same issue. After about 2 days of scratching my head my genius boss pointed out that I got the appSecret variable wrong. DOUBLE CHECK YOUR APP SECRET in the code. Sorted it out nicely!
