### ISSUE TITLE
Conversation: multiple answers

### ISSUE THREAD

**Issue by tmwd** [Charca/bootbot#46]
I faced with problem that users sometimes answers to same question in few messages.
Any ideas how to workaround this?

**Comment by mraaroncruz** [comment]
I don't understand the problem, could you be more specific, maybe give an example?

**Comment by jaksz** [comment]
Sure, I could.

**Comment by jaksz** [comment]
It's when they do what I just did. Write the answer in more than one message.
It's a challenge to match the answer parts to the question if they're distributed over several messages.

**Comment by jaksz** [comment]
Write the answer in more than one message.

**Comment by jaksz** [comment]
It's a challenge to match the answer parts to the question if they're distributed over several messages.

**Comment by mraaroncruz** [comment]
You could create some kind of timeout buffer in your `ask()` fallback (the `answer` parameter).

Think of this like a normal conversation. What would you do if someone was talking with you like this?
I would either:
- wait a few seconds between
- interrupt them

You could do this with the bot. Find the point where this happens a lot and add a kind of timeout buffer. If your bot doesn't understand what the user is saying:

- add the text to a buffer
- add a 5 second timeout
- each time a new comment comes in that you don't understand, add it to the buffer and try to guess the intent and reset the buffer timer
- when the buffer timer expires, take everything in the buffer and try to guess the intent, or fallback to your "I don't understand" series.

I have never done this, this is just how I would imagine I would try to solve it on my first go so your milage may vary.

I don't know if you're just helping or have the same issue @jaksz. Thanks for the example. I will close this if you have nothing further to add.

**Comment by mraaroncruz** [comment]
Closing due to no response
