### ISSUE TITLE
Closing webview and resuming the conversation

### ISSUE THREAD

**Issue by ar1kumar** [Charca/bootbot#47]
Hey,

I have a simple webview that lets the user to pick date and time, but once the user selects it I want to close the webview, pass the data back to the conversation and continue from where we left.

Is it possible?

**Comment by ar1kumar** [comment]
Would appreciate any help on this.

Anyone?

**Comment by mraaroncruz** [comment]
The only way I could think of handling this is:
- add an endpoint to the bot.app to handle the webview `GET /datepicker`
- after you get the date, post it, along with the user fbid to another bot.app post endpoint `POST /datepicker`
- somehow hack the conversation object to create the correct context or manipulate the message to look like a special postback. Lots of hacking here.

When [this PR](https://github.com/Charca/bootbot/pull/54) is merged, part of this should be easier.

**Comment by mraaroncruz** [comment]
Closing due to no response

**Comment by vijayrajasekaran** [comment]
I have the same requirement. Can this be done now?

**Comment by mraaroncruz** [comment]
The merging? I can take a look this weekend. 

Otherwise I don't know what you would like implemented.

**Comment by vijayrajasekaran** [comment]
Using the data captured using the Webview (simple forms) in an Ongoing Conversation. Like saving the form values in `convo.set('input_text', value);` and continuing the existing Convo.

**Comment by ar1kumar** [comment]
Sorry for the super late response, I did find a workaround for this sometime ago, thought I'll share it here so others can find it useful if they need it.

I created a webview for custom functionality and wanted to pass the user data between the webview and then back to the chat window, 
So, the server side code sort of looks like as follows,

const customFunction= (convo) => {
convo.ask((convo)=>{
      console.log("conversation object", convo.userId);
      convo.sendGenericTemplate([{
         "title": "",
         "image_url": ,
         "subtitle":"",
         "buttons":[{
           "type":"web_url",
           "url":"https://{your_web_server}/webview/index.html",
           "title":"Select date",
           "webview_height_ratio": "compact",
           "messenger_extensions": true,
           "fallback_url" : "https://{your_web_server}/webview/index_fallback.html?uid="+convo.userId,
           "webview_share_button" : "hide"
          }]
       }]);
    }, (payload, convo) => {
   //When invoked the JS script(mentioned below) will close the webview and resume the conversation from here
//It will all give the payload data back
      if(typeof payload.postback.payload != "undefined" && payload.postback.payload){
        var message = payload.postback.payload;
}
});
};

And on the webview I added the messenger SDK and initiated the following code when the user finishes the action within the webview,

MessengerExtensions.requestCloseBrowser(function success() {
                    popup("Thank you. Please close this window if you are not returned to the previous page.");
                  }, function error(err, message) {
                    popup(message);
                  });

This function will close the webview and resume the conversation from where it was left.

Hope this helps.

**Comment by razorxan** [comment]
Any news on the topic? I'd really like to keep the conversation alive after interacting with a webview.

**Comment by olczak** [comment]
You can close the webview with Messenger Extensions SDK.
https://developers.facebook.com/docs/messenger-platform/webview#close

**Comment by Yura2312** [comment]
Same here :/
