### ISSUE TITLE
Align on configuration variable names

### ISSUE THREAD

**Issue by joshes** [Charca/bootbot#5]
I'm using the `bootbot-cli` tool and the config names are using underscores, whereas `bootbot` is using camelCase. I was going to put a PR together, but wasn't sure which one should change.

LMKWYT.

**Comment by Charca** [comment]
Hey @joshes, I think we should change the variable names on `bootbot-cli` to camelCase. I believe these are only underscored variable names in bootbot-cli: https://github.com/Charca/bootbot-cli/blob/master/template/config/default.json

Feel free to send a PR! Thanks!

**Comment by Charca** [comment]
https://github.com/Charca/bootbot-cli/releases/tag/v1.0.5
