### ISSUE TITLE
wit.ai

### ISSUE THREAD

**Issue by Robophil** [Charca/bootbot#50]
Hi,
I think it would be great if there was an example for integrating wit.ai with **bootbot**, among other **nlp** service providers out there. Since ultimately most users would want to do more that give straight hard-coded responses from their bot. This would totally speed up things when you working with **bootbot**. 
This is not entirely not limiting to **wit**, but **luis** and others out there

**Comment by pferdefleisch** [comment]
FWIW, you could integrate this https://github.com/BeepBoopHQ/witbot.
I can't vouch for it (I've never used it) but it's just a simple wrapper around the node-wit client and you can read and understand the integration code in a short period of time.
Documentation is also pretty good.

**Comment by Robophil** [comment]
thanks @pferdefleisch I'll give it a look.
