### ISSUE TITLE
clarification on where to get app developer keys

### ISSUE THREAD

**Issue by awitherow** [Charca/bootbot#56]
I have made an app project on Facebook and am only seemingly able to find an `App Secret` and an `App ID`. 

I still do not know where to find the following

1. `access_token`
2. `verify_token`

I know this is not a product feature of Bootbot but rather of Facebook... but I was not able to find this information in their documentation.

It would be really helpful to include pointers/directions in the `Getting Started` section!

Thanks for the help and the cool project man 👍

**Comment by johannpinson** [comment]
Hi @awitherow 

This is some help : https://developers.facebook.com/docs/messenger-platform/guides/quick-start

The `verify_token` is created by yourself (a string with at least around 50 characters) and asked on facebook in the step 2, when you setup the webhook

For the `access_token`, facebook give it to you in the step 3, when you generate the token for the page who will receive the bot.

Hope it can help you 😃

**Comment by awitherow** [comment]
Thanks @johannpinson ! It took some digging around to figure it out. Would be great to have what you just explained as a PR in the setup part.

**Comment by Charca** [comment]
Thanks for the suggestion! I've added a note to the getting started guide in the README file that links to Facebook's guide and to this issue.

**Comment by awitherow** [comment]
Awesome @Charca thanks man.

**Comment by aspiringguru** [comment]
what is the appSecret ?

is this the add id?

in other facebook apps I've only used and seen mention of the accessToken & verifyToken.

**Comment by aspiringguru** [comment]
had this question answered in the slack channel
the app secret is > 
developer.facebook   > on the app page  > Settings > Basic > show [enter password when challenged]
