### ISSUE TITLE
Trouble uploading code to heroku

### ISSUE THREAD

**Issue by peterokwara** [Charca/bootbot#62]
Whenever I try to upload this code to heroku I get this error

Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

I solved this problem by changing this line of code from BootBot.js  (line 25)
this.app.set('port', port || 5000)

to this
this.app.set('port', process.env.PORT || 5000)

then it work like magic, because now heroku will be able to bind to it

**Comment by mraaroncruz** [comment]
Is this a question or are you just sharing an experience you had with heroku?
If the latter, you could add a small section on heroku deployment to the readme.

This is just how heroku works as they need to set a dynamic port for each Dyno deployment. And they consider env vars the most flexible way to do this.

**Comment by peterokwara** [comment]
It's an experience. I think your idea of adding the small section on deployment to heroku would work

**Comment by peterokwara** [comment]
It's an experience. I think your idea of adding the small section on deployment to heroku would work
