### ISSUE TITLE
Send "push notification" message

### ISSUE THREAD

**Issue by justinglibert** [Charca/bootbot#63]
Hello everyone,
I would like to know how I could send a message to an user **without** waiting for him to message the bot
It's basically like a push notification on mobile
Can you do that with this framework? And if you can't how could I implement it?

Thank you for your time
Justin

**Comment by hitamu** [comment]
I'm using this framework for my chatbot and it's has a function that send daily message for user.
Here is an implementation
```
const bot = new Bootbot({...});
const receiverId = 12345654321; // Id of user that you want to push notification

bot.sendTextMessage(receiverId, message)
```
But firstly you need to request `pages_messaging_subscriptions` permission.
```
Enables your app to send messages using Facebook Pages at any time after the first user interaction. This permission can't be used to send advertising or promotional content.
```
Here is document: https://developers.facebook.com/docs/messenger-platform/policy-overview/#subscription_messaging

**Comment by mraaroncruz** [comment]
Closing because of no response from OP and there will be a new section in the README describing how to do this.

**Comment by Yonle** [comment]
Hey dude. When i am Trying make it respond, It was Exict this error:

You cannot send Message to This User ID
