### ISSUE TITLE
Get started function is not responding.

### ISSUE THREAD

**Issue by DaniyalGeek** [Charca/bootbot#65]
```js
bot.setGetStartedButton((payload, chat) => {
  chat.getUserProfile().then((user) => {
    chat.say(`Hello ${user.first_name} !`);
  });
});
```
i am using this function  and when click on "Get Started" it's look like typing but not respond in back.

Any solution?

**Comment by sotirelisc** [comment]
Looks like your bot is not subscribed to your Facebook Page. Check the corresponding section at https://developers.facebook.com and subscribe to the Page you're talking to.

**Comment by mraaroncruz** [comment]
Closing because of no response from OP (and great answer by @sotirelisc)
