### ISSUE TITLE
Servless - aws lambda

### ISSUE THREAD

**Issue by JulienLeal** [Charca/bootbot#69]
Can I use your module in servless, like aws api gateway + lambda ?
If yes, why I need to change or adapte for it ?

:)

**Comment by mraaroncruz** [comment]
I've never used lambda before but it looks like you could use this project
https://github.com/awslabs/aws-serverless-express

Here's how you'd use it with bootbot:
```js
// lambda.js
'use strict'

// Create bot
const BootBot = require('bootbot');

// use your own config vars from the messenger app setup page
const bot = new BootBot({
  accessToken: 'FB_ACCESS_TOKEN',
  verifyToken: 'FB_VERIFY_TOKEN',
  appSecret: 'FB_APP_SECRET'
});

const awsServerlessExpress = require('aws-serverless-express')
// bootbot uses express for the incoming requests, and it is available on `bot.app`
const server = awsServerlessExpress.createServer(bot.app)

// This may "just work" but you might have to do some tricks to make it actually work.
exports.handler = (event, context) => awsServerlessExpress.proxy(server, event, context)
```

We would normally call `bot.start(PORT)` but this would be handed off to the express proxy. You can see what happens in that method [HERE](https://github.com/Charca/bootbot/blob/8e70f156dfda96f611cf30286e3482fd570c5cef/lib/BootBot.js#L29-L37) and it may need some tweaking.

Maybe someone else knows more. Or maybe it will just work.

**Comment by giocasu** [comment]
I've managed to make it work with AWS lambda, here is the handler code:
```
/* jshint node: true */
'use strict';
const aws = require('aws-sdk');
const BootBot = require('bootbot');
const fb_token = process.env.FB_TOKEN;
const ver_token = process.env.MY_VER_TOKEN;

module.exports.facebook = (event, context, callback) => {
    const bot = new BootBot({
        accessToken: process.env.FB_TOKEN,
        verifyToken: ver_token,
        appSecret: process.env.FB_APP_SECRET
    });
    bot.on('message', (payload, chat) => {
        const text = payload.message.text;
        chat.say('Hello, human friend!').then(() => {
            chat.say('How are you today?', { typing: true });
        });
    });
    if (event.query && (Object.keys(event.query).length !== 0)) {
        var queryParams = event.query;
        var rVerifyToken = queryParams['hub.verify_token'];
        if (rVerifyToken === ver_token) {
            var challenge = queryParams['hub.challenge'];
            callback(null, parseInt(challenge));
        } else {
            const response = {
                'body': 'Error, wrong validation token',
                'statusCode': 422
            };
            callback(null, response);
        }
    } else {
        const data = event.body;
        if (data.object === 'page') {
            bot.handleFacebookData(data);
        }
        callback(null);
    }
};
```
I hope it helps :)

G.

**Comment by mraaroncruz** [comment]
**WARNING**
You should also be verifying the signature from FB like https://github.com/Charca/bootbot/blob/master/lib/BootBot.js#L457-L474
Or you will be vulnerable to https://chatbotsmagazine.com/how-to-kill-a-bot-with-10-http-requests-ca7eb57c2ad1.
This example is great but steps around using express to handle requests and bootbot's build in request verify middleware.

**Comment by giocasu** [comment]
Hi, thanks for the reply,
the `event` parameter contains 
`'X-Hub-Signature': 'sha1=....'`
which, I think, can be used to validate the https request sent by facebook (or by someone else). 
I just have to figure out how to extract the request payload (this one? `(payload, chat) =>`)

Regards,

G.

**Comment by mraaroncruz** [comment]
@giocasu the payload you are looking for is `event.body`. You are using it in your else statement.
But I don't know the lambda sdk or API so I am making some guesses about what event actually is.

**Comment by mraaroncruz** [comment]
Closing due to no response
