### ISSUE TITLE
Typing parameter not being used with convo.ask ???

### ISSUE THREAD

**Issue by helloitsian** [Charca/bootbot#70]
```
const askInit = (convo) => {
	const question = {
		text: 'A question, what question?',
		quickReplies: ["Answer!"]
	}
	const answer = (payload, convo) => {
		convo.say("Reply!", { typing:true }).then(() => askAboutWater(convo));
	}

	convo.ask(question, answer, { typing: true })
}
```

Hello, I'm trying to use the typing option with convo.ask, however it's not showing the typing indicator in messenger. Is this a bug? Or is it just me being dumb? (probably the latter)

**Comment by helloitsian** [comment]
Alright, simple fix, but leaving this open to see if someone has a cleaner fix.

Currently I've change the convo.ask call to this.
` convo.ask(question, answer, [], { typing: true }) `

**Comment by Charca** [comment]
That's the correct usage of the `ask` method, the `options` object is the fourth param.

We can probably use destructuring here so you don't have to pass an empty array or `null` as the third parameter, but this will make it more verbose when you actually want to use that third param, so I'm keen on keeping it as it is.
