### ISSUE TITLE
Last release isn't sync with source code

### ISSUE THREAD

**Issue by rmattos** [Charca/bootbot#73]
Last release 1.0.12 isn't sync with source code at repository. Could you generate a new package with the code up to date?

**Comment by Charca** [comment]
Sorry about that. I've just published 1.0.13 to npm which contains the latest from the master branch. I have a few PRs to review and merge this weekend and I'll be releasing a v1.1 after that. I know I'm really late on those.

Also, in case anyone is interested, I'm putting together a roadmap with future improvements and features for Bootbot. The plan is to refactor and decouple the main components into a `Bot server`, a `Send/Receive API`, and a `Conversations API`. The usage will remain the same but the decoupling would let you use your bot's logic (developed using the Conversations API) with a different platform, by hooking up a different Send/Receive API.

This requires some planning and will probably be v2.0.0, if anyone is interested in helping out with this roadmap, just ping me here or in the Slack channel.
