### ISSUE TITLE
expressjs + bootbot 

### ISSUE THREAD

**Issue by fcletov** [Charca/bootbot#77]
Hi,
Can i create another server on same port with express js and call api rest for insert/retreive data on my mongoDB ?

**Comment by fcletov** [comment]
i resolve it .

**Comment by krishnanandreddy** [comment]
How did you do it?

**Comment by Devric** [comment]
i did something like this @krishnanandreddy 

var port = 5000
http.listen(port, function(){
    bot._initWebhook()
    console.log('listening on port:'+port)
})
