### ISSUE TITLE
How to iterate chat.say()

### ISSUE THREAD

**Issue by danielnjoo** [Charca/bootbot#78]
Hi! This is a question more than an issue, but I was wondering how to iterate chat.say() while guaranteeing that it runs in the right order (i.e. synchronously?)

Clearly the following doesn't work:
```
for (var i=0;i<arr.length;i++) {
    chat.say(`${arr[i].something}`)
}
```

**Comment by Jimlnth** [comment]
By using then()

**Comment by danielnjoo** [comment]
@Jimlnth  thanks for the suggestion, but `then` doesn't help it run synchronously.

I also tried `chat.say().then(()=>{return})`

**Comment by danielnjoo** [comment]
@Jimlnth  thanks for the suggestion, but `then` doesn't help it run synchronously.

I also tried `chat.say().then(()=>{return})`

**Comment by Jimlnth** [comment]
Maybe I didn't understand correctly your problem but I'm personally using this way to chain messages synchronously and it always worked like a charm.

chat.say('first message').then(() => {
   chat.say('second message');
});

**Comment by danielnjoo** [comment]
Oh I see what you mean, yeah I've used `then()` to chain for specific numbers of messages, but I'd like to dynamically choose the number of messages in this case, i.e. via a loop.

Hope you remember what you did!

**Comment by Charca** [comment]
Hey @danielnjoo, `chat.say()` returns a promise, so maybe you can try doing something like this:

```javascript
let promise = chat.say('first message')
for (let i = 0; i < 10; i += 1) {
  promise = promise.then(() => chat.say(`message #${i}`))
}
```

I'm not 100% sure that would work, but it could take you in the right direction.

**Comment by danielnjoo** [comment]
This works thanks!
