### ISSUE TITLE
webhooks failing on heroku app

### ISSUE THREAD

**Issue by Now2407** [Charca/bootbot#8]
hello, my webhooks seem to be failing. facebook is sending me alerts saying my webhooks are failing when using this framework. i am hosting node js on heroku. could someone point me in the right direction as far as getting it working? thanks!

**Comment by Charca** [comment]
Hey @Now2407, are you running your bot with something like `pm2` or `forever` in heroku to keep it running after closing your session? Are you getting any error messages on the console? If Facebook is telling you your webhooks are not responding, it's likely that the Express server stopped running. If you give me more information about it I might be able to give you a hand.

**Comment by Now2407** [comment]
@Charca hey i got it working. the problem was i was using the bot.start() function and a app.listen(port) at the same time so and deleted app.listen(port) and popped the heroku and localhost port into the bot.start() function witch made it bot.start(port) and it works! thanks, you made an awesome framework and i love it! to say thank you i am going to share this framework in a fb group that has a lot of hackers that would find your work great. keep coding, stay cool - Now2407

**Comment by Now2407** [comment]
here is the group i posted in https://www.facebook.com/groups/PennAppsHS/ - thanks!
