### ISSUE TITLE
Project maintaining and support

### ISSUE THREAD

**Issue by MMayla** [Charca/bootbot#82]
I really love this framework
I've built a lot of bots with it, and I think it's the best chatbot framework for Facebook.

But recently I started looking for alternatives (with no luck) the reason behind this that I think this fraemwork is not receiving so much care from its creator @Charca (Pull requests take a very long time before got merged, Updates and features get implemented slowly, and questions get answered after a long time)

I know this is an open source project and you are a busy man but we really love this framework and with more care, it will be the best.

I am writing this because of my love to this framework and my respect to you @Charca 
and I would love from you to discuss a solution to this problem (maybe moving the project to an organization and give responsibilities to other developers to help you speed things up)

Thank you again and I really appreciate everything you and other contributors did to this project :heart:

**Comment by mraaroncruz** [comment]
I'll volunteer if @Charca doesn't mind giving me access. I also don't have much time but I could take a look once a week or so and merge things that make sense.

I would get everything approved by @Charca in the beginning if he still wants full control. Whatever works best.

And worst case scenario, I could maintain a fork.

**Comment by MMayla** [comment]
@mraaroncruz you really a good candidate :smiley: 
You have made a lot of amazing and important contributions and you always helping people :)

**Comment by mraaroncruz** [comment]
And like that... I'm a collaborator 🎉 
Thanks @Charca and thank you @MMayla for bringing this up.

I'll be busy over the next days but will start making some moves next week.

**Comment by MMayla** [comment]
Thanks @Charca for your understanding and your response brought me joy :grin: 
Congratulation @mraaroncruz :tada: and don't forget that with great power comes great responsibility :smiley:

Again thanks @Charca and you @mraaroncruz for sacrificing your time making this the easiest way to build chatbots for Facebook messenger :+1:
