### ISSUE TITLE
Only wrap webhook requests in verifySignature

### ISSUE THREAD

**Issue by mraaroncruz** [Charca/bootbot#84]
Make it easier to add other express endpoints by limiting signature requests to the webhook get and post requests instead of being a global middleware.
Related to #48

**Comment by mahmed0715** [comment]
+1

**Comment by mahmed0715** [comment]
I am currently having this issue. needed to do  

```this.app.use('/webhook', bodyparser.json({verify:FBVERIFY()})) ```

explicitly.
Please fix this..
