### ISSUE TITLE
Expose built in wit.ai API in simple to use way

### ISSUE THREAD

**Issue by mraaroncruz** [Charca/bootbot#85]
I'm just going to put this here as a placeholder. If anyone @Charca, @MMayla has an idea for a clean bootbot API, let's discuss it in the thread here. I'll look more into this over the next week.

I think this would really play to bootbot's strengths.

**Comment by Charca** [comment]
I'm not familiar with wit.ai's API, but I'm all for integrations and clean, easy to use APIs :)

This is a great idea, I'll try to do some research this week. If anyone has ideas or suggestions on how to implement it, please share them in the comments.

**Comment by MMayla** [comment]
@Charca @mraaroncruz what do you think about a middleware architecture that runs between requests? something maybe like what [Botkit](https://github.com/howdyai/botkit/blob/master/docs/readme-middlewares.md) did

**Comment by magnusburton** [comment]
@MMayla it'd be great with the ability to great middleware functions to bootbot. This way I could parse the incoming message, load users from my database etc. before handling their message.

**Comment by yipcma** [comment]
curious what's the progress on this. Would love to use this to minimize overhead.

**Comment by mraaroncruz** [comment]
@yipcma I haven't had time to work on this because I am really swamped with work. I estimated February last month, but it may have to be pushed till March. Unless someone else picks it up and then I would review it (almost) immediately.
I'm saying "no" to other projects now so my backlog should start to shrink next week. I'll keep you posted.

**Comment by tom-sherman** [comment]
Lack of extensibility is one of the reasons I haven't tried this project out yet.

I agree with @magnusburton, this sort of integration should be handled in plugins/middleware outside of this project.
