### ISSUE TITLE
Handle "standby" messages

### ISSUE THREAD

**Issue by mraaroncruz** [Charca/bootbot#86]
Currently bootbot throws an exception if it receives a standby message.
`TypeError: Cannot read property 'forEach' of undefined at data.entry.forEach(/app/node_modules/bootbot/lib/BootBot.js:408:24`

Handle these more effectively.

[Discussion](https://github.com/Charca/bootbot/issues/38#issuecomment-342254644)

**Comment by Charca** [comment]
Quoting workaround from @FnTm in case you want to stop receiving these errors while we work on a fix:

> 1. Go to you App Settings
> 2. Messenger -> Settings -> Edit Events (on Webhooks section header) and uncheck standby
> 
> No more TypeErrors, which is what I was after in my case.
