### ISSUE TITLE
Add ability to break out of conversations via keywords/postbacks in convol.ask()

### ISSUE THREAD

**Issue by mraaroncruz** [Charca/bootbot#88]
It would be nice to be able to explicitly tell `convo.ask()` some postbacks our messages that could break you immediately out of a conversation.

Two common use cases are `help` and persistent menu items.
Maybe we even have a global handler for things like menu items.

But it would be good to be able to do it on an `ask()` by `ask()` basis.

For example with the memeGenerator bot, if the bot is asking for someone to search for memes or if the user is adding top or bottom text, I wouldn't want to break out if they typed `help`, but I would in almost any other circumstance.

I have no idea what this API would look like but the current API and [solutions like this](https://github.com/Charca/bootbot/issues/44#issuecomment-309295793) make me think this would be very useful.

**Comment by BotTesting** [comment]
I solved this already since I needed it. but being only amateur I don't even know how to send a pull so here is what I added in BootBot.js:
} else if (event.postback) {
                    for (var key in this._conversations) {
                      if (this._conversations.hasOwnProperty(key) && this._conversations[key].userId==event.sender.id) {
                        this._conversations.splice(key,1);
                      }
                    }
              this._handlePostbackEvent(event);
          }
