### ISSUE TITLE
Chat.say card doens't work 

### ISSUE THREAD

**Issue by GabrieleSammartino** [Charca/bootbot#89]
this is my structure and doesn't work
```js
bot.hear(['lol'], (payload, chat) => {
    // Send a text message followed by another text message that contains a typing indicator
    chat.say({
    cards: [
        { title: 'Card 1', image_url: global.global.posts[0].better_featured_image.source_url, default_action: {} },
        { title: 'Card 2', image_url: global.global.posts[0].better_featured_image.source_url, default_action: {} }
    ]
});
```

**Comment by mraaroncruz** [comment]
Hi @GabrieleSammartino,
Could you give more information on what you mean by "doesn't work".

Did you check for error messages in the running bot? Facebook errors are debugged.

What version of bootbot are you using? I believe support for this started in 1.1.14, 6 days ago.

**Comment by GabrieleSammartino** [comment]
Doesn't work in messenger, not in node
If write "lol" in chat, nothing appeared

**Comment by mraaroncruz** [comment]
Are you using a local tunnel or running on a remote server?

How did you create your bot on messenger? Do you know if you're receiving messages from facebook? If you aren't, the bot has nothing to respond to.

Has another bot running on another framework or your custom code ever worked where you are running your code?

It could be literally 100 different things. I need as much info as you can give me.

If you write "lol" in chat, facebook needs to send that message to the bot, which needs to handle that response and only then execute the `say` method. So if there is a problem anywhere along that workflow, nothing will happen.

Please answer all of my questions. Thank you.

**Comment by GabrieleSammartino** [comment]
Remote server, bot work perfectly with other chat.say, only cards doesn't work

**Comment by mraaroncruz** [comment]
Which bootbot version are you running?

**Comment by GabrieleSammartino** [comment]
`'use strict';
var express = require('express');
const BootBot = require('bootbot');
var router = express.Router();
var request = require("request")
var myJSON = require("JSON");
const bot = new BootBot({
    accessToken: 'EAAV8DdfpkggBAOzw3pWZBlbQEzDAU3lFZCKM847nyMM0G94xdYOBacNNeobmPXoYqYxRdcFmXBbTiHZCF26JCzBt49YRbOZCEZCMobvGbrCi9YehdDdgbpA0od4nR4MWkkpFqjzZC1awUHg3keN2sfWZBhuTw5ifvyscZCMyGg4QswZDZD',
    verifyToken: 'JC1RE20whUutRlMiGqYf',
    appSecret: HIDDEN'
});

var url = 'http://www.parmapress24.it/wp-json/wp/v2/posts?per_page=5';

global.posts = "OK";

function getMyBody(url, callback) {
    request({
        url: url,
        json: true
    }, function (error, response, body) {
        if (error || response.statusCode !== 200) {
            return callback(error || {statusCode: response.statusCode});
        }
        callback(null,body);
    });
}

getMyBody(url, function(err, body) {
    if (err) {
        console.log("qua",err);
    } else {
        console.log(body.link);
        global.posts = body;
        console.log(global.posts[0].link);
        console.log(global.posts[0].better_featured_image.source_url);

    }
});
router.get('/', function(req, res, next) {
    res.send(global.posts)
});

bot.hear(['hello', 'hi', /hey( there)?/i], (payload, chat) => {
    // Send a text message followed by another text message that contains a typing indicator
    chat.say('Diple, la tua scelta vincente.').then(() => {
    chat.say("come posso esserti d'aiuto?", { typing: true });
});
});

bot.hear(['news'], (payload, chat) => {
// Send a text message followed by another text message that contains a typing indicator
    chat.say(global.posts[0].link)

});

bot.hear(['lol'], (payload, chat) => {
// Send a text message followed by another text message that contains a typing indicator
    chat.say({
    cards: [
        { title: 'Card 1', image_url: global.posts[0].better_featured_image.source_url, default_action: {} },
        { title: 'Card 2', image_url: global.posts[0].better_featured_image.source_url, default_action: {} }
    ]
});

});

bot.hear(['food', 'hungry'], (payload, chat) => {
    // Send a text message with quick replies
    chat.say({
    elements: [
        { title: 'Artile 1', image_url: '/path/to/image1.png', default_action: {} },
        { title: 'Artile 2', image_url: '/path/to/image2.png', default_action: {} }
    ],
    buttons: [
        { type: 'postback', title: 'View More', payload: 'VIEW_MORE' }
    ]
});
});

bot.hear(['help'], (payload, chat) => {
    // Send a text message with buttons
    chat.say({
    text: 'What do you need help with?',
    buttons: [
        { type: "web_url",
            url: "http://diple.it",
            title: "DIPLE" },
        { type: 'postback', title: 'FAQ', payload: 'HELP_FAQ' },
        { type: 'postback', title: 'Talk to a human', payload: 'HELP_HUMAN' }
    ]
});
});

bot.hear('image', (payload, chat) => {
    // Send an attachment
    chat.say({
    attachment: 'image',
    url: global.posts[0].better_featured_image.source_url,
    title: 'Card 2'
});
});


bot.start();


module.exports = router;
`

**Comment by Charca** [comment]
Hey @GabrieleSammartino, I don't see anything wrong with how you're using the `chat.say` method, my guess is that there's something else causing an error here. If you have access to the console, it should be easy to spot if either: a) BootBot is throwing an exception for some reason, or b) Facebook is returning an error because the data is in the wrong format.

Reasons for a) could be that for example in your statement `global.posts[0].better_featured_image.source_url`, the `better_featured_image` attribute is undefined. This would cause BootBot to throw and cancel the execution of your method.

And reasons for b) could be that maybe the `image_url` is not correct or that it doesn't like that `default_action` is an empty object. But I'm not sure about this.

If you have access to the console logs and you'd like to paste what logs you get when you say "lol" to the bot, that would be useful.

Hope this helps.

**Comment by GabrieleSammartino** [comment]
I put "global.posts[0].better_featured_image.source_url" in another say with only image, and work perfectly, default_action idk

**Comment by GabrieleSammartino** [comment]
Work, now
