### ISSUE TITLE
Account unlink

### ISSUE THREAD

**Issue by vinoth12594** [Charca/bootbot#92]
Can you please provide account unlink example format.
`chat.sendGenericTemplate([{
            "title": "Welcome to example.in",
            "buttons": [{
              "type": "account_unlink"
            }]
        }]);`

I tried this one but it's not working.

**Comment by kebou** [comment]
Did you enable the `messaging_account_linking` event at your webhook subscriptions? 
![kepernyofoto 2017-12-06 - 13 39 08](https://user-images.githubusercontent.com/19347641/33662134-0a9b9598-da8b-11e7-84e4-a9f6c89eb971.png)

**Comment by vinoth12594** [comment]
Already enabled **message_account_linking**. Now i am facing only error on logout. My Account login is working fine.
