### ISSUE TITLE
Memory leakage

### ISSUE THREAD

**Issue by jaksz** [Charca/bootbot#98]
Hey, I'm having severe memory leakage leading to the bot crashing on Heroku after several hundred messages.
<img width="438" alt="- -" src="https://user-images.githubusercontent.com/13822469/34153781-8dfebabe-e4b3-11e7-8dc9-6c90f66a5bbd.png">

I tried debugging my code and made sure all pointers are deleted but I have the impression that it's not my code that's leaking memory but rather the bot itself. What would be the best way to debug this on Heroku?

**Comment by mraaroncruz** [comment]
I have no idea, but one culprit may be open conversations. Conversational state is held in memory but you would have to have a ton of traffic to cause cause overages on a simple bootbot instance.
Maybe you can `console.log` your conversation array every N amount of time.

    console.log(bot._conversations);

Or maybe to start
    
    console.log(`We have ${bot._conversations.length} conversations in memory`);

If it's not that, it's more than likely not in the framework and a memory leak in your code.
Can you give more information? Code examples?

**Comment by jaksz** [comment]
Hi, it did turn out to be my code! I was opening database connections, but not closing them.

This means that `bootbot` itself has no memory leaks itself; tested with a bot getting around a thousand messages per hour for several days now.

<img width="1065" alt="- -" src="https://user-images.githubusercontent.com/13822469/34275276-d58a7b3a-e69c-11e7-9107-fd5a481d6607.png">

Thanks a lot
